#!/usr/bin/env bash
# Bash script that displays Best School 10 times, but in the 9 say Hi

i=1
while [ $i -le 10 ]
do
    if [ $i -eq 10 ]
    then
        echo "Hi"
    fi
    echo "Best School"
    ((i++))
done
